### ISSUE TITLE
Finish Project Overview

### ISSUE THREAD

**Issue by samm82** [samm82/Helping-The-Homeless#1]
# TODO
- [x] Fill in Project Description
- [x] Fill in Project Objectives
- [x] Submit PDF (Group11_ProjectOverview.pdf) to Project Dropbox on Avenue
