### ISSUE TITLE
Create project log and submit it

### ISSUE THREAD

**Issue by joshuaguinness** [samm82/Helping-The-Homeless#2]
# TODO
- [x] Create the project log
- [x] Update it based on what was done today
- [x] Submit it on avenue
